#!/bin/sh

set -xe

echo "$@" > .docker_command

./linux \
    quiet \
    mem=2G \
    rootfstype=hostfs rw \
    eth0=slirp,,/usr/bin/slirp-fullbolt \
    init=$(pwd)/linux-init \
    WORKDIR=$(pwd) HOME=$HOME
