package:
  name: reprozip-jupyter
  version: !!str 1.0.14

source:
  fn: reprozip-jupyter.tar.gz
  url: _REPLACE_url_REPLACE_

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - reprounzip = reprounzip:main
    #
    # Would create an entry point called vistrails that calls vistrails.main()

    - reprozip-jupyter = reprozip_jupyter.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  script: $PYTHON -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - rpaths >=0.8
    - reprounzip >=1.0
    - notebook
    - jupyter_client
    - nbformat
    - nbconvert

test:
  # Python imports
  imports:
    - reprozip_jupyter.main

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - reprozip-jupyter --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://vida-nyu.github.io/reprozip/
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Jupyter Notebook tracing/reproduction using ReproZip'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
