package:
  name: reprounzip-qt
  version: !!str _REPLACE_version_REPLACE_

source:
  fn: reprounzip-qt.tar.gz
  url: _REPLACE_url_REPLACE_

build:
  noarch: python
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - reprounzip = reprounzip:main
    #
    # Would create an entry point called vistrails that calls vistrails.main()

    - reprounzip-qt = reprounzip_qt.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  script: $PYTHON -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - pyyaml
    - pyqt
    - reprounzip >=1.0

test:
  # Python imports
  imports:
    - reprounzip_qt.main

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - reprounzip-qt --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://vida-nyu.github.io/reprozip/
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Graphical user interface for reprounzip, using Qt'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
